### ISSUE TITLE
Factorio 0.17

### ISSUE THREAD

**Issue by OlegKrikun** [J3n50m4t/HighSpeedTrain#1]
Hi! Please add support for Factorio 0.17 =)

**Comment by J3n50m4t** [comment]
Fixed it in https://github.com/J3n50m4t/HighSpeedTrain/commit/e643961a2d39a61d8d9c411fdf268fb251216f51

See latest releases or check Factorio Updates.. Hope everything is correct, because I don't have any time to play anymore.
